
#ifndef GLOBAL_H_INCLUDED

#define SCREEN_WIDTH (640)
#define SCREEN_HEIGHT (480)
#define GAME_SCREEN_WIDTH  (13*TILE_WIDTH)
#define GAME_SCREEN_HEIGHT  (SCREEN_HEIGHT -2*SCORE_PANE_HEIGHT)

#define SCORE_PANE_HEIGHT (40)
#define SCORE_PANE_WIDTH (GAME_SCREEN_WIDTH)

#define TILE_WIDTH 44
#define TILE_HEIGHT 22

#define BASE_PADDLE_WIDTH 128
#define BASE_PADDLE_HEIGHT 22

#define PADDLE_OFFSET_FROM_TOP 350
#define PADDLE_SPEED 5

#define BALL_HEIGHT 10
#define BALL_WIDTH 10
#define BALL_SPEED_X 3
#define BALL_SPEED_Y 3

#define RESPAWN_TIME_IN_FRAMES 60

#define FPS 60
#define SPF (1./FPS)
#endif
